# Generated by Django 4.2.11 on 2024-05-20 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer_post',
            name='buyit',
            field=models.ManyToManyField(blank=True, related_name='buyit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consumer_post',
            name='dontbuyit',
            field=models.ManyToManyField(blank=True, related_name='dontbuyit', to=settings.AUTH_USER_MODEL),
        ),
    ]
