# Generated by Django 4.2.11 on 2024-05-20 08:02

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_img', models.ImageField(blank=True, default='image/user.png', upload_to='user/')),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('남성', 'M'), ('여성', 'F')], max_length=10, null=True)),
                ('job', models.CharField(blank=True, choices=[('직장인', '직장인'), ('학생', '학생'), ('자영업', '자영업'), ('프리랜서', '프리랜서'), ('주부', '주부'), ('은퇴자', '은퇴자'), ('무직', '무직'), ('기타', '기타')], max_length=10, null=True)),
                ('salary', models.CharField(blank=True, choices=[('200', '200만원 이하'), ('300', '201만원 ~ 300만원'), ('400', '301만원 ~ 400만원'), ('500', '401만원 ~ 500만원'), ('600', '501만원 ~ 600만원'), ('601', '601만원 이상')], max_length=10, null=True)),
                ('favorite_bank', models.CharField(blank=True, choices=[('SC제일은행', 'SC제일은행'), ('경남은행', '경남은행'), ('광주은행', '광주은행'), ('국민은행', '국민은행'), ('기업은행', '기업은행'), ('농협은행', '농협은행'), ('대구은행', '대구은행'), ('부산은행', '부산은행'), ('수협은행', '수협은행'), ('신한은행', '신한은행'), ('외환은행', '외환은행'), ('우리은행', '우리은행'), ('전북은행', '전북은행'), ('제주은행', '제주은행'), ('카카오뱅크', '카카오뱅크'), ('케이뱅크', '케이뱅크'), ('토스뱅크', '토스뱅크'), ('하나은행', '하나은행'), ('한국산업은행', '한국산업은행'), ('한국스탠다드차타드은행', '한국스탠다드차타드은행'), ('한국시티은행', '한국시티은행'), ('기타', '기타')], max_length=20, null=True)),
                ('user_type', models.CharField(blank=True, max_length=10, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
